apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ctfd
  namespace: ctf
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ctfd
  namespace: ctf
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ctfd:latest
  source:
    type: Git
    git:
      uri: 'https://github.com/psehgaft/CTFd'
    contextDir: /
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-312
      forcePull: true
  postCommit: {}
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
